comment:  Avalon-v1-PPOAC2
seed: 0
env:
  name: Avalon-v1
max_steps: 200000
test:
  steps: 40000
  episodes: 10
discount: 0.99
batch_size: 8
hidden_dim: 128
exploration_noise: 0.0565
optim_lr: 0.0001838
# load: runs/run_831
capture_freq: 1000000